version: "3"

services:
  server-app:
    env_file: .env
    build:
      context: .
    ports:
      - "4000:3000"
    volumes:
      - ./shared:/var/www/shared
    depends_on:
      - postgres
      - pgadmin
    networks:
      - snake

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    networks:
      - snake

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_LISTEN_PORT: $PGADMIN_LISTEN_PORT
    restart: always
    ports:
      - "8080:${PGADMIN_LISTEN_PORT}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - snake

volumes:
  pgadmin-data:

networks:
  snake:
    driver: bridge
