name: Test

on:
  pull_request:
  push:
    branches:
      - snake-56-ci/cd

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
  deploy:
    runs-on: [ self-hosted, linux, x64 ]
    strategy:
      matrix:
        node-version: [ 14.18.0 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
      - run: npm build:container:all
